# Generated by Django 2.2.5 on 2020-06-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200622_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielinks',
            old_name='type',
            new_name='movie_link_choice',
        ),
    ]
